### ISSUE TITLE
In shell mode, `ascii` crashed

### ISSUE THREAD

**Issue by Pollux3737** [Sup3Legacy/FerrOS#3]
While in the shell, the `ascii` command fails : 
![image](https://user-images.githubusercontent.com/29065455/107862914-80aa1000-6e50-11eb-91f8-566b34935b4f.png)

**Comment by Sup3Legacy** [comment]
I think it has something to do with some casts (int->float, it seems). I'm investigating.

**Comment by samsa1** [comment]
Doesn't exists anymore
